[package]
name = "to-do-list"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version="4.5.33", features = ["derive"] }
color-eyre = "0.6.3"
serde =  { version ="1.0.219", features = ["derive"] }
serde_json = "1.0.140"
